# Generated by Django 3.1.3 on 2022-11-14 03:35

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageDeRedirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_url', models.CharField(max_length=200, verbose_name='Nom sur bilodeau.co/')),
                ('url', models.URLField(max_length=2000, verbose_name='Lien URL vers')),
            ],
        ),
        migrations.CreateModel(
            name='RedirectionInfolettre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('image', models.ImageField(default='team_pics/default.jpg', upload_to='team_pics', validators=[home.models.validate_image], verbose_name='Image')),
                ('lienlinkedin', models.CharField(blank=True, max_length=500, verbose_name='Lien LinkedIn')),
            ],
        ),
        migrations.CreateModel(
            name='TextePageDAccueil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('un_a', models.CharField(max_length=200, verbose_name='1A')),
                ('un_b', models.TextField(max_length=1000, verbose_name='1B')),
                ('deux_a', models.CharField(max_length=200, verbose_name='2A')),
                ('deux_b', models.TextField(max_length=1000, verbose_name='2B')),
                ('trois_a', models.CharField(max_length=200, verbose_name='3A')),
                ('trois_b', models.TextField(max_length=1000, verbose_name='3B')),
            ],
        ),
    ]
